<h2>Abeeha</h2>
<h2>L1F18BSCS7204</h2>
<h2>Assignment no 2</h2>

<h3>TASK 1<br>Create a 4X2 integer array and Prints its attributes</h3>

In [26]:
import numpy as np

In [27]:
twoD = np.array ([[1,2],[3,4],[5,6],[7,8]])
print(twoD)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
print(twoD.shape)

(4, 2)


In [29]:
print(twoD.size)

8


In [30]:
print(twoD.ndim)

2


In [31]:
print(twoD.dtype)

int32


In [32]:
print(type(twoD))

<class 'numpy.ndarray'>


<h3>TASK 2<br> Create a 5X2 integer array from a range between 100 to 200 such that the difference between 
each element is 10
</h3>

In [35]:
arr = np.arange(100,200,10)
twoD = arr.reshape(5,2)
print(twoD)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


<h3>TASK 3<br>  Following is the provided numPy array. return array of items in the third column from all 
rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
</h3>

In [42]:
twoDarr = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(twoDarr)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [94]:
 print(twoDarr[:,2])


[33 66 99]


 <h3>TASK 4<br>  Return array of odd rows and even columns from below numpy array
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

</h3>

In [56]:
a = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48], [51,54,57,60]])
print(a)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [59]:
print(a[::2, 1::2])

[[ 6 12]
 [30 36]
 [54 60]]


 <h3>TASK 5<br>  Create a result array by adding the following two NumPy arrays. Next, modify the result 
array by calculating the square of each element
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
</h3>

In [68]:
onearr = np.array([[5,6,9], [21,18,27]])
twoarr = np.array([[15,33,24],[4,7,1]])
print(onearr)
print(twoarr)

[[ 5  6  9]
 [21 18 27]]
[[15 33 24]
 [ 4  7  1]]


In [69]:
add = onearr+twoarr
print(add)

[[20 39 33]
 [25 25 28]]


In [70]:
for i in add:
    print(i**2)

[ 400 1521 1089]
[625 625 784]


 <h3>TASK 6<br>  Create an 8X3 integer array from a range between 10 to 34 such that the difference between 
each element is 1 and then Split the array into four equal-sized sub-arrays.

</h3>

In [95]:
arr = np.arange(10,34,1)
print(arr)
arr = arr.reshape(8,3)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [96]:
x = np.split(arr,4)
print(x)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


 <h3>TASK 7<br>Sort following NumPy array first by the second row, then by the second columns
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
</h3>

In [97]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(arr)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [123]:
tworow = arr[:,arr[1,:].argsort()]
print(tworow)

[[34 22 73]
 [12 43 82]
 [53 94 66]]


In [124]:
twocolumn = arr[arr[:,1].argsort()]
print(twocolumn)

[[34 22 73]
 [12 43 82]
 [53 94 66]]


 <h3>TASK 8<br> Print max from axis 0 and min from axis 1 from the following 2-D array.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
</h3>

In [103]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(arr)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [104]:
a = np.max(arr,0)
print(a)

[82 94 73]


In [105]:
b = np.min(arr,1)
print(b)

[34 12 53]


 <h3>TASK 9<br>  Delete the second column from a given array and insert the following new column in its 
place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])
</h3>

In [106]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(arr)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [107]:
x = np.delete(arr,1,axis=1)
print(x)

[[34 73]
 [82 12]
 [53 66]]


In [109]:
a = np.array([[10,10,10]])
y = np.insert(x,1,a,axis=1)
print(y)

[[34 10 73]
 [82 10 12]
 [53 10 66]]
